name: Cypress Test


# event to trigger the workflow manually
on:

  workflow_dispatch:

  push:
    # Trigger the workflow when a push is made to the main branch
    branches:
      - main

    # Trigger the workflow when a pull request is made to the main branch
  pull_request:
    branches:
      - main
  

jobs:
  ui_test_chrome:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code from the repository to the runner
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      # Step 3: Debug directory structure
      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la cypress/e2e/config/
          cat cypress/e2e/config/constants.js

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          npm ci
          npm list cypress

      # Step 5: Run cypress tests for chrome
      - name: Run cypress tests for chrome
        run: |
          npx cypress verify
          npm run test:login

      # Step 6: Upload test results as artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UI Test Report
          path: |
            cypress/results/junit/combined-report.xml
            cypress/results/cypress-mochawesome-reporter/
            cypress/videos/
            cypress/screenshots/
          retention-days: 1
